import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const reviews = [
  {
    userName: "John Doe",
    userImage: null,
    rating: 5,
    content: "Absolutely amazing! Smooth experience and thoughtful design.",
  },
  {
    userName: "Jane Smith",
    userImage: null,
    rating: 4,
    content: "Great features, but could use a dark mode update.",
  },
  {
    userName: "Alex Johnson",
    rating: 3,
    content: "It's okay, but crashes occasionally on my old phone.",
  },
  {
    userName: "Emily Davis",
    userImage: null,
    rating: 5,
    content: "Best in class. Highly recommend!",
  },
  {
    userName: "Michael Brown",
    rating: 2,
    content: "Too many ads recently. Disappointed.",
  },
  {
    userName: "Priya Patel",
    userImage: null,
    rating: 4,
    content: "Love the regular updates and the speed improvements.",
  },
  {
    userName: "Carlos Santana",
    rating: 5,
    content: "Exactly what I needed for daily use. Intuitive and reliable.",
  },
  {
    userName: "Lin Wei",
    rating: 4,
    content: "Good balance of features without feeling overwhelming.",
  },
];

const screenshotLibrary = {
  social: [
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
  ],
  productivity: [
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
  ],
  games: [
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
  ],
  kids: [
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
  ],
  entertainment: [
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
  ],
  travel: [
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
  ],
  finance: [
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
  ],
  shopping: [
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
  ],
  health: [
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
  ],
  education: [
    "/placeholders/screen-1.svg",
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
  ],
  photography: [
    "/placeholders/screen-2.svg",
    "/placeholders/screen-3.svg",
    "/placeholders/screen-1.svg",
  ],
};

const apps = [
  {
    title: "WhatsApp Messenger",
    developer: "WhatsApp LLC",
    iconUrl: "/icons/app1.jpg",
    description: "WhatsApp from Meta is a FREE messaging and video calling app. It's used by over 2B people in more than 180 countries. It's simple, reliable, and private, so you can easily keep in touch with your friends and family.",
    rating: 4.6,
    downloads: "5B+",
    category: "Social",
    isInstalled: true,
    size: "45 MB",
    version: "2.23.10.77",
    updatedAt: new Date("2025-01-08"),
    screenshots: screenshotLibrary.social,
  },
  {
    title: "Instagram",
    developer: "Meta Platforms, Inc.",
    iconUrl: "/icons/app2.jpg",
    description: "Bringing you closer to the people and things you love. Share reels, stories, and moments with friends all over the world.",
    rating: 4.5,
    downloads: "5B+",
    category: "Social",
    isInstalled: false,
    size: "55 MB",
    version: "280.0.0.12.115",
    updatedAt: new Date("2025-01-02"),
    screenshots: screenshotLibrary.social,
  },
  {
    title: "Telegram",
    developer: "Telegram FZ-LLC",
    iconUrl: "/icons/app3.jpg",
    description: "Pure instant messaging — simple, fast, secure, and synced across all your devices. One of the world's top 10 most downloaded apps with over 800 million active users.",
    rating: 4.4,
    downloads: "1B+",
    category: "Social",
    isInstalled: false,
    size: "35 MB",
    version: "9.6.5",
    updatedAt: new Date("2024-12-14"),
    screenshots: screenshotLibrary.social,
  },
  {
    title: "Spotify",
    developer: "Spotify AB",
    iconUrl: "/icons/app4.jpg",
    description: "The best way to listen to music and podcasts on mobile or tablet. Discover playlists made for every moment and mood.",
    rating: 4.5,
    downloads: "1B+",
    category: "Entertainment",
    isInstalled: true,
    size: "30 MB",
    version: "8.8.32.500",
    updatedAt: new Date("2025-01-10"),
    screenshots: screenshotLibrary.entertainment,
  },
  {
    title: "Notion",
    developer: "Notion Labs, Inc.",
    iconUrl: "/icons/app5.jpg",
    description: "A single space where you can think, write, and plan. Capture thoughts, manage projects, or even run an entire company.",
    rating: 4.8,
    downloads: "10M+",
    category: "Productivity",
    isInstalled: false,
    size: "20 MB",
    version: "0.6.150",
    updatedAt: new Date("2024-12-25"),
    screenshots: screenshotLibrary.productivity,
  },
  {
    title: "Todoist",
    developer: "Doist",
    iconUrl: "/icons/app6.jpg",
    description: "The world's #1 to-do list and task manager app. Organize work and life with natural language and recurring reminders.",
    rating: 4.7,
    downloads: "50M+",
    category: "Productivity",
    isInstalled: false,
    size: "15 MB",
    version: "10.0.5",
    updatedAt: new Date("2025-01-12"),
    screenshots: screenshotLibrary.productivity,
  },
  {
    title: "Google Drive",
    developer: "Google LLC",
    iconUrl: "/icons/app7.jpg",
    description: "A safe place to back up and access all your files from any device. Easily invite others to view, edit, or leave comments.",
    rating: 4.4,
    downloads: "5B+",
    category: "Productivity",
    isInstalled: true,
    size: "60 MB",
    version: "2.23.181.2",
    updatedAt: new Date("2024-12-30"),
    screenshots: screenshotLibrary.productivity,
  },
  {
    title: "PUBG Mobile",
    developer: "Level Infinite",
    iconUrl: "/icons/app8.jpg",
    description: "Drop in, gear up, and compete. Survive epic 100-player classic battles, payload mode, and fast-paced 4v4 team deathmatch.",
    rating: 4.3,
    downloads: "1B+",
    category: "Games",
    isInstalled: false,
    size: "800 MB",
    version: "2.6.0",
    updatedAt: new Date("2024-12-22"),
    screenshots: screenshotLibrary.games,
  },
  {
    title: "Genshin Impact",
    developer: "miHoYo",
    iconUrl: "/icons/app9.jpg",
    description: "Step into Teyvat, a vast world teeming with life and elemental energy. Explore, fight, and unravel countless mysteries.",
    rating: 4.5,
    downloads: "100M+",
    category: "Games",
    isInstalled: false,
    size: "400 MB",
    version: "3.7.0",
    updatedAt: new Date("2024-12-28"),
    screenshots: screenshotLibrary.games,
  },
  {
    title: "Clash of Clans",
    developer: "Supercell",
    iconUrl: "/icons/app10.jpg",
    description: "Build your village, raise a clan, and compete in epic Clan Wars! Clash in friendly challenges or war leagues.",
    rating: 4.6,
    downloads: "500M+",
    category: "Games",
    isInstalled: true,
    size: "250 MB",
    version: "15.292.1",
    updatedAt: new Date("2025-01-09"),
    screenshots: screenshotLibrary.games,
  },
  {
    title: "YouTube Kids",
    developer: "Google LLC",
    iconUrl: "/icons/app11.jpg",
    description: "A contained video app made just for kids with family-friendly videos on all different topics.",
    rating: 4.4,
    downloads: "500M+",
    category: "Kids",
    isInstalled: false,
    size: "80 MB",
    version: "8.15.0",
    updatedAt: new Date("2024-12-18"),
    screenshots: screenshotLibrary.kids,
  },
  {
    title: "Khan Academy Kids",
    developer: "Khan Academy",
    iconUrl: "/icons/app12.jpg",
    description: "Free, fun educational program for children ages 2-8 with thousands of activities, books, songs, and games.",
    rating: 4.7,
    downloads: "10M+",
    category: "Kids",
    isInstalled: false,
    size: "120 MB",
    version: "5.1.0",
    updatedAt: new Date("2025-01-11"),
    screenshots: screenshotLibrary.kids,
  },
  {
    title: "PBS KIDS Video",
    developer: "PBS KIDS",
    iconUrl: "/placeholders/icon-green.svg",
    description: "Stream safe, educational shows from PBS KIDS featuring favorites like Daniel Tiger and Wild Kratts.",
    rating: 4.5,
    downloads: "100M+",
    category: "Kids",
    isInstalled: false,
    size: "90 MB",
    version: "5.5.0",
    updatedAt: new Date("2025-01-10"),
    screenshots: screenshotLibrary.kids,
  },
  {
    title: "Toca Life World",
    developer: "Toca Boca",
    iconUrl: "/placeholders/icon-orange.svg",
    description: "Create your own worlds and stories with customizable characters, pets, and hundreds of playsets.",
    rating: 4.4,
    downloads: "500M+",
    category: "Kids",
    isInstalled: false,
    size: "600 MB",
    version: "1.84",
    updatedAt: new Date("2024-12-27"),
    screenshots: screenshotLibrary.kids,
  },
  {
    title: "Google Maps",
    developer: "Google LLC",
    iconUrl: "/placeholders/icon-green.svg",
    description: "Real-time GPS navigation, traffic, and transit info. Explore local businesses and places to eat, drink, and visit.",
    rating: 4.3,
    downloads: "10B+",
    category: "Travel",
    isInstalled: true,
    size: "95 MB",
    version: "11.112.0101",
    updatedAt: new Date("2025-01-14"),
    screenshots: screenshotLibrary.travel,
  },
  {
    title: "Netflix",
    developer: "Netflix, Inc.",
    iconUrl: "/placeholders/icon-dark.svg",
    description: "Watch award-winning series, movies, documentaries, and mobile games. New titles added every week.",
    rating: 4.4,
    downloads: "1B+",
    category: "Entertainment",
    isInstalled: false,
    size: "75 MB",
    version: "16.25.0",
    updatedAt: new Date("2025-01-07"),
    screenshots: screenshotLibrary.entertainment,
  },
  {
    title: "Duolingo",
    developer: "Duolingo",
    iconUrl: "/placeholders/icon-green.svg",
    description: "Learn a new language with quick, fun lessons. Track progress, earn crowns, and practice speaking, reading, and listening.",
    rating: 4.7,
    downloads: "500M+",
    category: "Education",
    isInstalled: false,
    size: "52 MB",
    version: "5.119.3",
    updatedAt: new Date("2025-01-05"),
    screenshots: screenshotLibrary.education,
  },
  {
    title: "Slack",
    developer: "Slack Technologies",
    iconUrl: "/placeholders/icon-blue.svg",
    description: "Work faster with organized conversations, searchable history, and integrations with all your favorite tools.",
    rating: 4.2,
    downloads: "100M+",
    category: "Productivity",
    isInstalled: false,
    size: "110 MB",
    version: "24.01.10",
    updatedAt: new Date("2025-01-03"),
    screenshots: screenshotLibrary.productivity,
  },
  {
    title: "Canva",
    developer: "Canva",
    iconUrl: "/placeholders/icon-blue.svg",
    description: "Create stunning social posts, presentations, and videos in minutes with templates and simple drag-and-drop tools.",
    rating: 4.8,
    downloads: "100M+",
    category: "Photography",
    isInstalled: false,
    size: "40 MB",
    version: "2.248.0",
    updatedAt: new Date("2024-12-26"),
    screenshots: screenshotLibrary.photography,
  },
  {
    title: "Amazon Shopping",
    developer: "Amazon Mobile LLC",
    iconUrl: "/placeholders/icon-orange.svg",
    description: "Shop millions of products, track orders in real time, and access exclusive deals for Prime members.",
    rating: 4.5,
    downloads: "500M+",
    category: "Shopping",
    isInstalled: true,
    size: "70 MB",
    version: "26.1.4.100",
    updatedAt: new Date("2025-01-04"),
    screenshots: screenshotLibrary.shopping,
  },
  {
    title: "Strava",
    developer: "Strava Inc.",
    iconUrl: "/placeholders/icon-orange.svg",
    description: "Track runs, rides, and workouts with GPS. Join challenges, follow friends, and analyze performance with detailed stats.",
    rating: 4.6,
    downloads: "50M+",
    category: "Health & Fitness",
    isInstalled: false,
    size: "80 MB",
    version: "329.10",
    updatedAt: new Date("2025-01-06"),
    screenshots: screenshotLibrary.health,
  },
  {
    title: "TikTok",
    developer: "TikTok Pte. Ltd.",
    iconUrl: "/placeholders/icon-dark.svg",
    description: "Watch and create short-form videos with music, effects, and filters. Discover trends tailored to your interests.",
    rating: 4.4,
    downloads: "1B+",
    category: "Entertainment",
    isInstalled: false,
    size: "92 MB",
    version: "34.2.3",
    updatedAt: new Date("2025-01-13"),
    screenshots: screenshotLibrary.entertainment,
  },
  {
    title: "Headspace",
    developer: "Headspace for Meditation, Mindfulness and Sleep",
    iconUrl: "/placeholders/icon-orange.svg",
    description: "Meditation and mindfulness for stress, sleep, focus, and fitness. Short guided sessions and sleepcasts for better rest.",
    rating: 4.8,
    downloads: "10M+",
    category: "Health & Fitness",
    isInstalled: false,
    size: "35 MB",
    version: "4.235.0",
    updatedAt: new Date("2025-01-01"),
    screenshots: screenshotLibrary.health,
  },
  {
    title: "Minecraft",
    developer: "Mojang",
    iconUrl: "/placeholders/icon-green.svg",
    description: "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles, solo or with friends.",
    rating: 4.6,
    downloads: "50M+",
    category: "Games",
    isInstalled: false,
    size: "600 MB",
    version: "1.20.73",
    updatedAt: new Date("2024-12-20"),
    screenshots: screenshotLibrary.games,
  },
  {
    title: "Adobe Lightroom",
    developer: "Adobe",
    iconUrl: "/placeholders/icon-blue.svg",
    description: "Powerful photo & video editor with presets, tone curves, and cloud sync. Edit anywhere and stay organized.",
    rating: 4.7,
    downloads: "100M+",
    category: "Photography",
    isInstalled: false,
    size: "120 MB",
    version: "9.1.0",
    updatedAt: new Date("2024-12-29"),
    screenshots: screenshotLibrary.photography,
  },
];

async function main() {
  await prisma.review.deleteMany();
  await prisma.screenshot.deleteMany();
  await prisma.app.deleteMany();

  for (const [index, app] of apps.entries()) {
    const { screenshots, ...appData } = app;
    const screenshotsToUse = screenshots?.length ? screenshots : [app.iconUrl];
    const offset = index % reviews.length;
    const reviewSet = Array.from({ length: 4 }, (_, i) => {
      const template = reviews[(offset + i) % reviews.length];
      return {
        ...template,
        content: template.content.replace("{title}", app.title),
      };
    });

    const createdApp = await prisma.app.create({
      data: {
        ...appData,
        screenshots: {
          create: screenshotsToUse.map((url) => ({ url })),
        },
        reviews: {
          create: reviewSet,
        },
      },
    });
    console.log(`Created app with id: ${createdApp.id}`);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error("Seed failed", error);
    await prisma.$disconnect();
    process.exit(1);
  });
